enabled: true

#These values multiply the normalized knockback vector.
#The knockback vector is measured in blocks per tick
ground_horizontal_multiplier: 0.42
ground_vertical_multiplier: 0.3
air_horizontal_multiplier: 0.42
air_vertical_multiplier: 0.3

#Sprint knockback controls
sprint_multiplier_horizontal: 2
sprint_multiplier_vertical: 1.3
#How much should sprint knockback be affected by the attacker's yaw? Range: 0.0-1.0
sprint_yaw_factor: 0.5

fall_multiplier_horizontal: 0.3
fall_multiplier_vertical: -0.1

fall_toggle_max_height: 2
fall_toggle_min_height: 0.1
